---
deployment:
  tasks:
   -export DEPLOYPATH=/home/taylsqya/public_html/
   - /bin/cp index.html $DEPLOYPATH
   - /bin/cp style.css $DEPLOYPATH
  - /bin/cp favicon.ico $DEPLOYPATH
  - /bin/cp hex.html $DEPLOYPATH
  - /bin/cp app.js $DEPLOYPATH
  /bin/cp hex.js $DEPLOYPATH
  /bin/cp stylesforhex.css $DEPLOYPATH
  /bin/cp simple.html $DEPLOYPATH